### ISSUE TITLE
unable to log in...?

### ISSUE THREAD

**Issue by xpseudonym** [rubenarakelyan/mondo-qif-exporter#1]
Hi Ruben, just sent you a thank you for this tool.

But, now I try to log-in it doesn't seem to work.

I've clicked on the 'Accounts' link to the page 'https://mondoqifexporter.uk/accounts linked to https://auth.getmondo.co.uk/'
Then, clicked 'Authorise app' button
Then, entered my email address in the revealed text field
Then, pressed the 'Submit' button - repeatedly
Than, nothing happens

Any pointers would be great.

**Comment by xpseudonym** [comment]
I guess it's actually the 'https://auth.getmondo.co.uk/' page and that might not be anything to do with mondo-qif-exporter ?
Thanks

**Comment by rubenarakelyan** [comment]
At the moment, Mondo are not allowing anyone other than the app creator to use it by logging in with their Mondo username and password. Until they allow this, you'll have to download and host the app yourself...

**Comment by xpseudonym** [comment]
Thanks Ruben, that makes some sense.
But, just so I understand - you're saying, if I d/l the code and host it on my machine and log into the site on my machine, then effectively Mondo will see me as the app 'creator' (all credit to yourself) and Mondo will allow me to use it?

**Comment by rubenarakelyan** [comment]
Yeah, the thing that allows you to use it is getting your developer credentials from https://developer.getmondo.co.uk and setting up the app to use those (for which you'll need to host your own copy of the app). The one I'm hosting uses my developer credentials which means only I can use it for the moment until Mondo opens it up.

**Comment by xpseudonym** [comment]
Thx, will get to work :)
